name: herehear
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_tags: ^0.4.9+1
  textfield_tags: ^1.2.0
  firebase_storage: ^8.1.0
  cloud_firestore: ^2.2.0
  image_picker: ^0.7.5+2
  provider: ^5.0.0
  google_sign_in: ^5.0.3
  firebase_auth: ^1.2.0
  http: ^0.13.3
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  comment_box: ^0.0.16
  flutter_mentions: ^2.0.1
  flutter_signin_button: ^2.0.0
  weather: ^2.0.1
  syncfusion_flutter_charts: ^18.4.41
  swipeable_page_route: ^0.2.1
  multiple_stream_builder: ^2.0.0
  confirm_dialog: ^1.0.0


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
#     - images/a_dot_ham.jpeg
    - assets/images/profile.jpg
    - assets/images/sunny.png
    - assets/images/cloudy.png
    - assets/images/few_clouds.png
    - assets/images/few_clouds_night.png
    - assets/images/broken_clouds.png
    - assets/images/cloudy_night.png
    - assets/images/moon.png
    - assets/images/rain.png
    - assets/images/rain_night.png
    - assets/images/snow.png
    - assets/images/background_rain.png
    - assets/images/background_snow.png
    - assets/images/background_sunny.png
    - assets/images/background_night.png
    - assets/images/background_cloudy.png
    - assets/images/detail_sunny.png
    - assets/images/detail_cloudy.png
    - assets/images/detail_night.png
    - assets/images/detail_rain.png
    - assets/images/feelLike.png
    - assets/images/humidityLevel/humidity1.png
    - assets/images/humidityLevel/humidity2.png
    - assets/images/humidityLevel/humidity3.png
    - assets/images/humidityLevel/humidity4.png
    - assets/images/humidityLevel/humidity5.png
    - assets/images/humidityLevel/humidity6.png
    - assets/images/humidityLevel/humidity7.png
    - assets/images/humidityLevel/humidity8.png
    - assets/images/humidityLevel/humidity9.png
    - assets/images/humidityLevel/humidity10.png
    - assets/images/dustLevel/dust_good.png
    - assets/images/dustLevel/dust_notBad.png
    - assets/images/dustLevel/dust_bad.png
    - assets/images/dustLevel/dust_worst.png
    - assets/images/feelLike/feelLike_high.png
    - assets/images/feelLike/feelLike_middle.png
    - assets/images/feelLike/feelLike_low.png
    - assets/images/UV.png
    - assets/images/umbrella.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
